### ISSUE TITLE
Compiling on modern Linux

### ISSUE THREAD

**Issue by tissatussa** [alito/smallpotato#1]
I succeeded to compile your v0.7.0 source on 64-bit Linux !
I only had to adjust a few things, mainly adding 'extern' to some variables in 'pieces.h' and defining them in 'pieces.c'. Is a modern GCC compiler different ? Anyway, it plays a good game in my CuteChess GUI. Where can i find an opening book ? It fails to load ..

In 'sp.rc' is find many nice settings.
They could be options in the (CuteChess) config pane, i consider rewriting this engine into UCI, maybe just to learn some C !? Thanks for the code. Will you ever create a new version ?

[smallpotato-v0.7.0-fixed.zip](https://github.com/user-attachments/files/17958482/smallpotato-v0.7.0-fixed.zip)

![celluloid-shot0002](https://github.com/user-attachments/assets/b81d86b6-f217-4c3d-a45a-3485715db751)

[ i'm on Xubuntu 22.04 ]

**Comment by alito** [comment]
Thank you for taking a look and for sending your fixes. It used to compile in 64-bit but the C standards keep on plodding along so I'll see what needs to be updated.

The opening book is linked from the readme, but I also see that newer browsers refuse to download non-https content. The link to the 64-bit opening book should be https://organicrobot.com/smallpotato/book64.opn.bz2  I'll change the README to link there. Maybe I'll learn how to host it in Github too :)

I hadn't been planning to make more releases (this is a very old project, much older than Github) but I have come into some free time, so I'll definitely incorporate whatever you fixed (and whatever else you want to fix in the future).

**Comment by tissatussa** [comment]
> ..and whatever else you want to fix in the future..

well, the options file 'sp.rc' is logical but not handy : when adding 2 versions of Small Potato to the CuteChess GUI engine list, one with Book and one without, i have to create 2 folders with copies of your file set. The options better be in the CuteChess options pane. I can't help you with GitHub PRs / uploads / etc. .. i'm not familiar with that, i'm just a user of chess engines (and i gather their code) on Linux. Btw. here's the ChatGPT session which helped me to repair your code : https://chatgpt.com/share/674d818e-f648-8001-b7bf-1e66de8cce7f

**Comment by tissatussa** [comment]
Also the different search methods could be options.

**Comment by alito** [comment]
I incorporated your changes and pushed out a new version (0.7.1). Thank you very much for reporting.

Regarding using the CuteChess options, I'll have to take a look.

**Comment by tissatussa** [comment]
> Regarding using the CuteChess options, I'll have to take a look.

Options in the CuteChess GUI options pane are just auto-generated from the UCI options we see after the 'uci' command. So, creating those will make CuteChess show them.

I will now try your v0.7.1

**Comment by tissatussa** [comment]
> I will now try your v0.7.1

i get this error :

```
$ ./configure 
configure: error: cannot find required auxiliary files: compile
```

i don't remember having this issue with the previous version ..
i have gcc installed, even gcc-13

**Comment by alito** [comment]
Oof. My QA skills have gone to the dogs.

I added the `compile` script which the new autotools generates and bumped to 0.7.2. Hopefully it works this time.

Thank you for reporting! (Otherwise it could have stayed broken for another decade)

**Comment by tissatussa** [comment]
OK, now compiling went well : i get a valid v0.7.2 binary which runs fine in CuteChess.

My mistake about the CuteChess GUI options pane : i was referring to UCI but now i realise yours is XBoard based .. nevermind, CuteChess behaves the same i guess.
